// strings.ts — Import Center copy, {he,en} flat keys (contract C8).
//
// Wave-1 rule: components ship their own strings module in the same
// {he:{},en:{}} shape as src/lib/portalLocale.ts; Agent-OVERVIEW merges these
// into ownerLocale.ts in wave 2 (or they stay local; both are acceptable).
// Every key exists in BOTH locales. No internal jargon, no em-dashes.

export type ImporterLocale = 'he' | 'en'

const he = {
  'import.title': 'ייבוא גלריות',
  'import.subtitle': 'העברת גלריות ולקוחות מ־Pixieset (או מכל מקור אחר) אל Pixflow, צעד אחר צעד.',
  'import.provider.pixieset': 'Pixieset',
  'import.step1.title': 'שלב 1: ייצוא מהחשבון שלך ב־Pixieset',
  'import.step1.intro': 'ל־Pixieset אין חיבור ישיר בין מערכות, ולכן הייבוא מבוסס על הקבצים שאתם מייצאים בעצמכם מהחשבון שלכם. זה התהליך המלא והבטוח:',
  'import.step1.item1': 'ב־Pixieset Studio Manager: Contacts ואז Export כדי להוריד קובץ CSV של אנשי הקשר (עמודות שם, אימייל, חברה וכן הלאה).',
  'import.step1.item2': 'לכל גלריה (Collection): פתחו את הגלריה, בחרו Download והורידו קובץ ZIP באיכות Original (זמין במסלולים בתשלום). גלריות גדולות מפוצלות אוטומטית לכמה קבצי ZIP.',
  'import.step1.item3': 'אפשר גם להכין קובץ CSV פשוט של רשימת הגלריות: עמודות Collection Name, Client Name, Client Email, Collection URL, Date. אין ב־Pixieset ייצוא מוכן של רשימה כזו, ולכן מכינים אותה ידנית (למשל העתקה מהמסך לגיליון).',
  'import.step1.item4': 'סרטונים לא נכללים בייבוא הזה: ב־Pixieset מורידים אותם אחד אחד, ולכן מטפלים בהם בנפרד.',
  'import.step1.note': 'חשוב לדעת: הייבוא משתמש רק בקבצים שהורדתם בעצמכם מהחשבון שלכם. אנחנו לא מתחברים ל־Pixieset ולא אוספים משם מידע בשום דרך אחרת.',
  'import.step1.cta': 'יש לי את הקבצים, ממשיכים',
  'import.step2.title': 'שלב 2: העלאת קובץ ה־CSV',
  'import.step2.intro': 'העלו את קובץ הגלריות (או את קובץ אנשי הקשר). נזהה את העמודות, נציג את הרשימה, ונציע התאמה ללקוחות קיימים. שום דבר עדיין לא מיובא בשלב הזה.',
  'import.step2.choose': 'בחירת קובץ CSV',
  'import.step2.parsing': 'קורא את הקובץ...',
  'import.step2.contactsParsed': 'זוהה קובץ אנשי קשר: {count} אנשי קשר. כדי לייבא גלריות, העלו גם קובץ רשימת גלריות.',
  'import.step2.droppedPassword': 'עמודת סיסמה זוהתה בקובץ והוסרה. סיסמאות לא נשמרות אצלנו אף פעם.',
  'import.step2.ignoredHeaders': 'עמודות שלא זוהו ולא נעשה בהן שימוש:',
  'import.step2.tooBig': 'קובץ ה־CSV גדול מ־2MB. פצלו אותו לקבצים קטנים יותר.',
  'import.step2.empty': 'הקובץ ריק או שלא זוהתה בו עמודת שם גלריה.',
  'import.step2.table.collection': 'גלריה',
  'import.step2.table.client': 'לקוח בקובץ',
  'import.step2.table.match': 'התאמה',
  'import.step2.table.action': 'מה לעשות',
  'import.match.matched': 'הותאם',
  'import.match.ambiguous': 'דורש בדיקה',
  'import.match.unmatched': 'ללא התאמה',
  'import.match.create_new': 'לקוח חדש',
  'import.match.skip': 'דילוג',
  'import.action.map': 'שיוך ללקוח קיים',
  'import.action.create_new': 'יצירת לקוח חדש',
  'import.action.skip': 'לא לייבא',
  'import.action.pickClient': 'בחירת לקוח...',
  'import.step2.searchClient': 'חיפוש לקוח',
  'import.step2.cta': 'המשך לשיוך קבצי ZIP',
  'import.step2.unresolved': 'יש גלריות שעדיין מסומנות "דורש בדיקה" או "ללא התאמה". בחרו לכל אחת שיוך, לקוח חדש או דילוג.',
  'import.step3.title': 'שלב 3: שיוך קבצי ה־ZIP לגלריות',
  'import.step3.intro': 'העלו את קבצי ה־ZIP שהורדתם מ־Pixieset. נשייך אותם אוטומטית לפי שם, ואפשר לתקן ידנית. הקבצים נשארים אצלכם בדפדפן עד שלב ההרצה.',
  'import.step3.choose': 'בחירת קבצי ZIP',
  'import.step3.reading': 'קורא את תוכן ה־ZIP...',
  'import.step3.zipTooBig': 'קובץ ה־ZIP גדול מ־2GB ולכן לא ניתן לקרוא אותו בדפדפן בשלב זה. פצלו את ההורדה ב־Pixieset לקבצים קטנים יותר.',
  'import.step3.assignTo': 'שיוך לגלריה',
  'import.step3.unassigned': 'ללא שיוך',
  'import.step3.validFiles': 'תמונות תקינות',
  'import.step3.skipped': 'דולגו (תיקיות, קבצי מערכת)',
  'import.step3.rejected': 'נדחו',
  'import.step3.rejectedWhy': 'סיבות דחייה',
  'import.reject.traversal': 'נתיב חשוד בתוך הקובץ',
  'import.reject.absolute': 'נתיב מוחלט בתוך הקובץ',
  'import.reject.control_chars': 'שם קובץ לא תקין',
  'import.reject.empty': 'קובץ ריק',
  'import.reject.unsupported_type': 'סוג קובץ לא נתמך (רק JPG, PNG, WebP)',
  'import.reject.too_large': 'קובץ גדול מ־40MB',
  'import.reject.too_deep': 'תיקיות מקוננות מדי בתוך ה־ZIP',
  'import.reject.bomb_ratio': 'קובץ דחוס בצורה חריגה ולכן נחסם',
  'import.step3.totalWarning': 'סך התמונות חורג מ־10GB לריצה אחת. פצלו את הייבוא לכמה ריצות.',
  'import.step3.cta': 'הכול משויך, מעבר להרצה',
  'import.step3.needAssign': 'שייכו לפחות קובץ ZIP אחד לגלריה כדי להמשיך.',
  'import.step4.title': 'שלב 4: הרצת הייבוא',
  'import.step4.intro': 'לכל גלריה תיווצר גלריה חדשה בסטטוס טיוטה, והתמונות יועלו כמו בהעלאה רגילה. אפשר להשהות ולהמשיך בכל שלב.',
  'import.step4.dupPolicy': 'טיפול בכפילויות',
  'import.step4.dup.skip': 'דילוג על תמונות זהות (מומלץ)',
  'import.step4.dup.replace': 'החלפה (יתווסף בגרסה הבאה)',
  'import.step4.dup.copy': 'יצירת עותק (יתווסף בגרסה הבאה)',
  'import.step4.start': 'התחלת ייבוא',
  'import.step4.pause': 'השהיה',
  'import.step4.resume': 'המשך',
  'import.step4.cancel': 'ביטול',
  'import.step4.cancelNote': 'ביטול עוצר את הריצה בלבד. תמונות שכבר הועלו נשארות בגלריות.',
  'import.step4.running': 'מייבא...',
  'import.step4.paused': 'הייבוא מושהה',
  'import.step4.cancelled': 'הייבוא בוטל',
  'import.step4.collection': 'גלריה',
  'import.step4.progress': 'התקדמות',
  'import.step4.done': 'הועלו',
  'import.step4.dupSkipped': 'כפילויות שדולגו',
  'import.step4.failed': 'נכשלו',
  'import.step5.title': 'שלב 5: דוח ייבוא',
  'import.step5.intro': 'סיכום מלא של הריצה. גלריות חדשות נוצרו בסטטוס טיוטה, מוכנות לבדיקה ופרסום.',
  'import.step5.imported': 'הועלו',
  'import.step5.skipped': 'דולגו',
  'import.step5.failed': 'נכשלו',
  'import.step5.retry': 'ניסיון חוזר לקבצים שנכשלו',
  'import.step5.openGallery': 'פתיחת הגלריה',
  'import.step5.failures': 'פירוט כשלים',
  'import.step5.done': 'סיום',
  'import.common.back': 'חזרה',
  'import.common.loading': 'טוען...',
  'import.common.error': 'משהו השתבש. נסו שוב.',
  'import.common.retry': 'ניסיון חוזר',
  'import.common.empty': 'אין נתונים להצגה עדיין.',
  'import.common.files': 'קבצים',
  'import.common.close': 'סגירה',
} as const

type Keys = keyof typeof he

const en: Record<Keys, string> = {
  'import.title': 'Import galleries',
  'import.subtitle': 'Move galleries and clients from Pixieset (or any other source) into Pixflow, step by step.',
  'import.provider.pixieset': 'Pixieset',
  'import.step1.title': 'Step 1: Export from your Pixieset account',
  'import.step1.intro': 'Pixieset has no system-to-system connection, so the import is based on files you export yourself from your own account. This is the full, safe process:',
  'import.step1.item1': 'In Pixieset Studio Manager: Contacts, then Export, to download a CSV of your contacts (name, email, company and so on).',
  'import.step1.item2': 'For each collection: open it, choose Download, and get a ZIP at Original resolution (available on paid plans). Large collections are split into several ZIPs automatically.',
  'import.step1.item3': 'You can also prepare a simple collections CSV: columns Collection Name, Client Name, Client Email, Collection URL, Date. Pixieset has no ready-made export of this list, so it is prepared manually (for example, copied from the screen into a sheet).',
  'import.step1.item4': 'Videos are not part of this import: Pixieset only lets you download them one at a time, so handle them separately.',
  'import.step1.note': 'Important: the import uses only files you downloaded yourself from your own account. We never connect to Pixieset or collect anything from it in any other way.',
  'import.step1.cta': 'I have the files, continue',
  'import.step2.title': 'Step 2: Upload the CSV',
  'import.step2.intro': 'Upload the collections file (or the contacts file). We will detect the columns, show the list, and suggest matches to existing clients. Nothing is imported yet at this stage.',
  'import.step2.choose': 'Choose CSV file',
  'import.step2.parsing': 'Reading the file...',
  'import.step2.contactsParsed': 'Contacts file detected: {count} contacts. To import galleries, also upload a collections list CSV.',
  'import.step2.droppedPassword': 'A password column was detected in the file and removed. Passwords are never stored.',
  'import.step2.ignoredHeaders': 'Columns that were not recognized and were not used:',
  'import.step2.tooBig': 'The CSV is larger than 2MB. Split it into smaller files.',
  'import.step2.empty': 'The file is empty or no collection-name column was found.',
  'import.step2.table.collection': 'Collection',
  'import.step2.table.client': 'Client in file',
  'import.step2.table.match': 'Match',
  'import.step2.table.action': 'Action',
  'import.match.matched': 'Matched',
  'import.match.ambiguous': 'Needs review',
  'import.match.unmatched': 'No match',
  'import.match.create_new': 'New client',
  'import.match.skip': 'Skipped',
  'import.action.map': 'Map to existing client',
  'import.action.create_new': 'Create new client',
  'import.action.skip': 'Do not import',
  'import.action.pickClient': 'Pick a client...',
  'import.step2.searchClient': 'Search clients',
  'import.step2.cta': 'Continue to ZIP mapping',
  'import.step2.unresolved': 'Some collections are still marked "Needs review" or "No match". Choose map, new client, or skip for each one.',
  'import.step3.title': 'Step 3: Map the ZIP files to collections',
  'import.step3.intro': 'Upload the ZIPs you downloaded from Pixieset. We match them automatically by name, and you can fix any mapping manually. Files stay in your browser until the run step.',
  'import.step3.choose': 'Choose ZIP files',
  'import.step3.reading': 'Reading ZIP contents...',
  'import.step3.zipTooBig': 'This ZIP is larger than 2GB, which the browser cannot read at this stage. Split the download in Pixieset into smaller ZIPs.',
  'import.step3.assignTo': 'Assign to collection',
  'import.step3.unassigned': 'Unassigned',
  'import.step3.validFiles': 'Valid images',
  'import.step3.skipped': 'Skipped (folders, system files)',
  'import.step3.rejected': 'Rejected',
  'import.step3.rejectedWhy': 'Rejection reasons',
  'import.reject.traversal': 'Suspicious path inside the file',
  'import.reject.absolute': 'Absolute path inside the file',
  'import.reject.control_chars': 'Invalid file name',
  'import.reject.empty': 'Empty file',
  'import.reject.unsupported_type': 'Unsupported type (JPG, PNG, WebP only)',
  'import.reject.too_large': 'File larger than 40MB',
  'import.reject.too_deep': 'Folders nested too deep inside the ZIP',
  'import.reject.bomb_ratio': 'Abnormally compressed file, blocked for safety',
  'import.step3.totalWarning': 'Total images exceed 10GB for a single run. Split the import into several runs.',
  'import.step3.cta': 'Everything mapped, go to run',
  'import.step3.needAssign': 'Assign at least one ZIP to a collection to continue.',
  'import.step4.title': 'Step 4: Run the import',
  'import.step4.intro': 'A new draft gallery is created per collection, and photos upload through the regular upload engine. You can pause and resume at any point.',
  'import.step4.dupPolicy': 'Duplicate handling',
  'import.step4.dup.skip': 'Skip identical photos (recommended)',
  'import.step4.dup.replace': 'Replace (coming in a next version)',
  'import.step4.dup.copy': 'Create a copy (coming in a next version)',
  'import.step4.start': 'Start import',
  'import.step4.pause': 'Pause',
  'import.step4.resume': 'Resume',
  'import.step4.cancel': 'Cancel',
  'import.step4.cancelNote': 'Cancel only stops the run. Photos already uploaded stay in their galleries.',
  'import.step4.running': 'Importing...',
  'import.step4.paused': 'Import paused',
  'import.step4.cancelled': 'Import cancelled',
  'import.step4.collection': 'Collection',
  'import.step4.progress': 'Progress',
  'import.step4.done': 'Uploaded',
  'import.step4.dupSkipped': 'Duplicates skipped',
  'import.step4.failed': 'Failed',
  'import.step5.title': 'Step 5: Import report',
  'import.step5.intro': 'A full summary of the run. New galleries were created as drafts, ready for review and publishing.',
  'import.step5.imported': 'Uploaded',
  'import.step5.skipped': 'Skipped',
  'import.step5.failed': 'Failed',
  'import.step5.retry': 'Retry failed files',
  'import.step5.openGallery': 'Open gallery',
  'import.step5.failures': 'Failure details',
  'import.step5.done': 'Done',
  'import.common.back': 'Back',
  'import.common.loading': 'Loading...',
  'import.common.error': 'Something went wrong. Please try again.',
  'import.common.retry': 'Retry',
  'import.common.empty': 'Nothing to show yet.',
  'import.common.files': 'files',
  'import.common.close': 'Close',
}

export const IMPORTER_STRINGS: Record<ImporterLocale, Record<Keys, string>> = { he, en }

export type ImporterKey = Keys

export function makeT(locale: ImporterLocale) {
  const dict = IMPORTER_STRINGS[locale] ?? IMPORTER_STRINGS.he
  return (key: Keys, vars?: Record<string, string | number>): string => {
    let s: string = dict[key] ?? key
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(`{${k}}`, String(v))
    return s
  }
}

export function dirFor(locale: ImporterLocale): 'rtl' | 'ltr' {
  return locale === 'he' ? 'rtl' : 'ltr'
}
