// Shared UI kit (Editorial design system). Import from one place:
//   import { Button, Card, Badge } from '../components/ui'
export { Button } from './Button'
export type { ButtonProps } from './Button'
export { Card } from './Card'
export type { CardProps } from './Card'
export { Badge } from './Badge'
export type { BadgeProps } from './Badge'
export { Reveal } from './Reveal'
export type { RevealProps } from './Reveal'
export { Detect } from './Detect'
export type { DetectProps } from './Detect'
