// strings — local locale dictionary for the owner Global Search (contract C8).
//
// `src/lib/ownerLocale.ts` is being created concurrently by another agent, so
// this module follows the agreed wave-1 pattern: a local `{he,en}` flat-key
// dictionary with the same shape as portalLocale's STRINGS. The component
// receives `locale` as a prop (default 'he'); in wave 2 the integrator wires
// that prop from `useOwnerLocale()`. Every key exists in BOTH languages.
// Copy rules: no internal jargon, no long dashes, no mixed-direction strings.

import type { SearchLocale } from './searchLogic'

const STRINGS = {
  he: {
    'search.title': 'חיפוש',
    'search.subtitle': 'איתור לקוחות, גלריות ותמונות לפי שם, מיקום או מאפייני אירוע',
    'search.placeholder': 'חיפוש לפי שם לקוח, גלריה, מיקום או שם קובץ',
    'search.clear': 'ניקוי',
    'search.filters': 'סינון',
    'search.clearFilters': 'ניקוי סינון',
    'search.searching': 'מחפש…',
    'search.idleTitle': 'מה מחפשים היום?',
    'search.idleBody': 'הקלידו טקסט חופשי, או בחרו סינון כדי לדפדף בגלריות לפי מאפייני אירוע.',
    'search.emptyTitle': 'לא נמצאו תוצאות',
    'search.emptyBody': 'נסו ניסוח אחר, פחות סינונים, או בדקו את איות השם.',
    'search.error': 'החיפוש נכשל. בדקו את החיבור ונסו שוב.',
    'search.retry': 'ניסיון נוסף',
    'search.section.clients': 'לקוחות',
    'search.section.galleries': 'גלריות',
    'search.section.images': 'תמונות',
    'search.matched': 'התאמה:',
    'search.reason.name': 'שם',
    'search.reason.clientName': 'שם לקוח',
    'search.reason.eventLocation': 'מיקום',
    'search.reason.eventType': 'סוג אירוע',
    'search.reason.filename': 'שם קובץ',
    'search.reason.other': 'שדה נוסף',
    'search.imagesCap': 'מוצגות עד 60 תמונות תואמות',
    'search.imagesCount': 'תמונות',
    'search.openGallery': 'פתיחת גלריה',
    'search.openClient': 'פתיחת לקוח',
    'search.status.live': 'פורסם',
    'search.status.draft': 'טיוטה',
    'search.unassigned': 'ללא שיוך',
    'filter.client': 'לקוח',
    'filter.any': 'הכול',
    'filter.status': 'סטטוס',
    'filter.status.live': 'פורסם',
    'filter.status.draft': 'טיוטה',
    'filter.assigned': 'שיוך ללקוח',
    'filter.assigned.yes': 'משויכות',
    'filter.assigned.no': 'ללא שיוך',
    'filter.eventType': 'סוג אירוע',
    'filter.eventType.ph': 'למשל: חתונה',
    'filter.size': 'גודל אירוע',
    'filter.size.intimate': 'אינטימי (עד 50)',
    'filter.size.small': 'קטן (50 עד 150)',
    'filter.size.medium': 'בינוני (150 עד 500)',
    'filter.size.large': 'גדול (500 עד 2000)',
    'filter.size.massive': 'ענק (מעל 2000)',
    'filter.industry': 'תחום',
    'filter.industry.ph': 'למשל: הייטק',
    'filter.venue': 'סוג מקום',
    'filter.venue.indoor': 'מקורה',
    'filter.venue.outdoor': 'בחוץ',
    'filter.venue.mixed': 'משולב',
    'filter.time': 'שעות האירוע',
    'filter.time.day': 'יום',
    'filter.time.night': 'לילה',
    'filter.time.mixed': 'משולב',
    'filter.yearFrom': 'משנה',
    'filter.yearTo': 'עד שנה',
    'filter.keywords': 'מילות מפתח',
    'filter.keywords.ph': 'מופרדות בפסיק',
    'filter.imported': 'מקור ייבוא',
    'filter.imported.pixieset': 'Pixieset',
    'filter.imported.generic_csv': 'קובץ CSV',
    'filter.imported.local_folder': 'תיקייה מקומית',
  },
  en: {
    'search.title': 'Search',
    'search.subtitle': 'Find clients, galleries and photos by name, location or event details',
    'search.placeholder': 'Search by client, gallery, location or file name',
    'search.clear': 'Clear',
    'search.filters': 'Filters',
    'search.clearFilters': 'Clear filters',
    'search.searching': 'Searching…',
    'search.idleTitle': 'What are you looking for?',
    'search.idleBody': 'Type free text, or pick a filter to browse galleries by event details.',
    'search.emptyTitle': 'No results',
    'search.emptyBody': 'Try different wording, fewer filters, or check the spelling.',
    'search.error': 'Search failed. Check your connection and try again.',
    'search.retry': 'Try again',
    'search.section.clients': 'Clients',
    'search.section.galleries': 'Galleries',
    'search.section.images': 'Photos',
    'search.matched': 'Matched:',
    'search.reason.name': 'name',
    'search.reason.clientName': 'client name',
    'search.reason.eventLocation': 'location',
    'search.reason.eventType': 'event type',
    'search.reason.filename': 'file name',
    'search.reason.other': 'other field',
    'search.imagesCap': 'Showing up to 60 matching photos',
    'search.imagesCount': 'photos',
    'search.openGallery': 'Open gallery',
    'search.openClient': 'Open client',
    'search.status.live': 'Published',
    'search.status.draft': 'Draft',
    'search.unassigned': 'Unassigned',
    'filter.client': 'Client',
    'filter.any': 'All',
    'filter.status': 'Status',
    'filter.status.live': 'Published',
    'filter.status.draft': 'Draft',
    'filter.assigned': 'Client assignment',
    'filter.assigned.yes': 'Assigned',
    'filter.assigned.no': 'Unassigned',
    'filter.eventType': 'Event type',
    'filter.eventType.ph': 'e.g. wedding',
    'filter.size': 'Event size',
    'filter.size.intimate': 'Intimate (under 50)',
    'filter.size.small': 'Small (50 to 150)',
    'filter.size.medium': 'Medium (150 to 500)',
    'filter.size.large': 'Large (500 to 2000)',
    'filter.size.massive': 'Massive (over 2000)',
    'filter.industry': 'Industry',
    'filter.industry.ph': 'e.g. high-tech',
    'filter.venue': 'Venue type',
    'filter.venue.indoor': 'Indoor',
    'filter.venue.outdoor': 'Outdoor',
    'filter.venue.mixed': 'Mixed',
    'filter.time': 'Time of day',
    'filter.time.day': 'Day',
    'filter.time.night': 'Night',
    'filter.time.mixed': 'Mixed',
    'filter.yearFrom': 'From year',
    'filter.yearTo': 'To year',
    'filter.keywords': 'Keywords',
    'filter.keywords.ph': 'comma separated',
    'filter.imported': 'Import source',
    'filter.imported.pixieset': 'Pixieset',
    'filter.imported.generic_csv': 'CSV file',
    'filter.imported.local_folder': 'Local folder',
  },
} as const

export type SearchStringKey = keyof typeof STRINGS.he

/** Translate a key for the given locale. Unknown keys return the key itself. */
export function t(locale: SearchLocale, key: string): string {
  const dict: Record<string, string> = STRINGS[locale] ?? STRINGS.he
  return dict[key] ?? key
}

export function dirFor(locale: SearchLocale): 'rtl' | 'ltr' {
  return locale === 'he' ? 'rtl' : 'ltr'
}

export { STRINGS }
