-- ─────────────────────────────────────────────────────────────────────────────
-- 051_feed_plans.sql
-- The Feed Studio MVP — first piece of the AI Visual Operating System.
-- Stores generated Instagram feed plans per client. A plan = 9 posts with
-- captions, color assignments, themes, and reasoning. Generated by Claude
-- Sonnet over the client's top picks.
--
-- The architecture doc (§3.5) documents five canonical grid styles. The MVP
-- ships ONE: color_block_editorial. The `style` column is forward-compatible
-- for the other four (editorial_magazine, sandwich, pop_collage, billboard).
--
-- A `feed_plan` is generated once per (client, "month plan request"). The
-- photographer can regenerate at will; old plans stay in the table as audit
-- so we can later learn from accepted vs. discarded plans (Brand Brain v2).
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

CREATE TABLE IF NOT EXISTS feed_plans (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id     UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  client_id       UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  -- Which gallery_ids fed this plan. Stored as array so the plan can pull
  -- across multiple events when a client has many.
  source_gallery_ids UUID[] NOT NULL DEFAULT '{}',
  style           TEXT NOT NULL DEFAULT 'color_block_editorial'
                    CHECK (style IN ('color_block_editorial','editorial_magazine','sandwich','pop_collage','billboard')),
  -- The 9 posts. Each post: { image_id, caption, theme, color, reasoning, position }
  -- Stored as JSONB so the schema can evolve without migrations.
  posts           JSONB NOT NULL,
  -- Brand snapshot at generation time. Lets us trace decisions back to the
  -- brand profile that produced them.
  brand_snapshot  JSONB,
  -- The full Claude prompt + response for debug + audit. Keeps us honest.
  llm_trace       JSONB,
  -- Lifecycle: draft (just generated), accepted (photographer approved),
  -- rejected (photographer regenerated), published (live on IG).
  status          TEXT NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft','accepted','rejected','published')),
  generated_by    UUID,    -- the auth.uid() that triggered this generation
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  accepted_at     TIMESTAMPTZ,
  published_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS feed_plans_client_idx ON feed_plans(client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS feed_plans_business_idx ON feed_plans(business_id, created_at DESC);

ALTER TABLE feed_plans ENABLE ROW LEVEL SECURITY;

-- Photographer (authenticated) can read all their own plans.
CREATE POLICY feed_plans_owner_select ON feed_plans
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM businesses b
             WHERE b.id = feed_plans.business_id
               AND b.user_id = auth.uid())
  );

-- Photographer can insert + update their own plans.
CREATE POLICY feed_plans_owner_insert ON feed_plans
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM businesses b
             WHERE b.id = feed_plans.business_id
               AND b.user_id = auth.uid())
  );

CREATE POLICY feed_plans_owner_update ON feed_plans
  FOR UPDATE TO authenticated
  USING (
    EXISTS (SELECT 1 FROM businesses b
             WHERE b.id = feed_plans.business_id
               AND b.user_id = auth.uid())
  );

-- Anon (the public client dashboard, accessed via /<biz>/client/<id>/dashboard)
-- can read plans for their own client_id. The viewer is non-authenticated;
-- this is intentional — the photographer publishes the dashboard to the client
-- without an account. Status='accepted' or 'published' only — drafts are
-- photographer-internal.
CREATE POLICY feed_plans_public_select ON feed_plans
  FOR SELECT TO anon
  USING (status IN ('accepted','published'));

COMMIT;
