// tender/strings.ts — local strings module for the tender library (contract C8).
// Same {he,en} shape as portalLocale; Agent-OVERVIEW may merge these into
// ownerLocale.ts in wave 2, or they stay local permanently (both acceptable).
// Every key exists in BOTH locales. No em-dashes, no internal jargon.

export type Locale = 'he' | 'en'
export type Dir = 'rtl' | 'ltr'
export const dirFor = (l: Locale): Dir => (l === 'he' ? 'rtl' : 'ltr')

const he = {
  'tender.title': 'מאגר למכרזים',
  'tender.subtitle': 'סננו את הארכיון לפי מאפייני אירוע, אספו גלריות ותמונות לאוסף, וייצאו רשימה להצעה',
  'tender.search.placeholder': 'חיפוש לפי שם גלריה, לקוח או מיקום...',
  'tender.filters.event_type': 'סוג אירוע',
  'tender.filters.size': 'גודל אירוע',
  'tender.filters.industry': 'תעשייה',
  'tender.filters.industry.placeholder': 'למשל: הייטק, פיננסים...',
  'tender.filters.client': 'לקוח',
  'tender.filters.client.any': 'כל הלקוחות',
  'tender.filters.location': 'מיקום',
  'tender.filters.location.placeholder': 'עיר או מקום...',
  'tender.filters.venue': 'סוג מתחם',
  'tender.filters.time': 'שעות',
  'tender.filters.years': 'טווח שנים',
  'tender.filters.year_from': 'משנה',
  'tender.filters.year_to': 'עד שנה',
  'tender.filters.keywords': 'מילות מפתח',
  'tender.filters.keywords.placeholder': 'מופרדות בפסיק...',
  'tender.filters.any': 'הכל',
  'tender.filters.clear': 'נקה סינון',
  'tender.orientation': 'כיוון תמונה',
  'tender.orientation.any': 'הכל',
  'tender.orientation.portrait': 'לאורך',
  'tender.orientation.landscape': 'לרוחב',
  'tender.size.intimate': 'אינטימי (עד 50)',
  'tender.size.small': 'קטן (50-150)',
  'tender.size.medium': 'בינוני (150-500)',
  'tender.size.large': 'גדול (500-2000)',
  'tender.size.massive': 'ענק (2000+)',
  'tender.venue.indoor': 'מקורה',
  'tender.venue.outdoor': 'פתוח',
  'tender.venue.mixed': 'משולב',
  'tender.time.day': 'יום',
  'tender.time.night': 'לילה',
  'tender.time.mixed': 'משולב',
  'tender.results.count': 'גלריות',
  'tender.results.one': 'גלריה',
  'tender.results.empty': 'לא נמצאו גלריות התואמות לחיפוש',
  'tender.results.loading': 'מחפש...',
  'tender.results.error': 'החיפוש נכשל, נסו שוב',
  'tender.results.search_hint': 'הזינו חיפוש או בחרו סינון כדי לראות תוצאות',
  'tender.match.title': 'למה זה התאים:',
  'tender.match.name': 'שם הגלריה',
  'tender.match.client': 'לקוח',
  'tender.match.event_type': 'סוג אירוע',
  'tender.match.event_location': 'מיקום',
  'tender.match.event_size_bucket': 'גודל',
  'tender.match.industry': 'תעשייה',
  'tender.match.venue_type': 'מתחם',
  'tender.match.time_of_day': 'שעות',
  'tender.match.year': 'שנה',
  'tender.match.keywords': 'מילות מפתח',
  'tender.gallery.open': 'פתח גלריה',
  'tender.gallery.pick_images': 'בחר תמונות',
  'tender.gallery.close_images': 'סגור תמונות',
  'tender.gallery.add_to_collection': 'הוסף לאוסף',
  'tender.gallery.in_collection': 'באוסף',
  'tender.gallery.remove_from_collection': 'הסר מהאוסף',
  'tender.gallery.images': 'תמונות',
  'tender.gallery.status.live': 'פורסמה',
  'tender.gallery.status.draft': 'טיוטה',
  'tender.gallery.no_client': 'ללא לקוח',
  'tender.ai_order': 'מבוסס על ציון AI קיים',
  'tender.manual_order': 'לפי סדר הגלריה',
  'tender.unclassified': 'לא מסווג',
  'tender.classify': 'סווג אירוע',
  'tender.classify.close': 'סגור',
  'tender.classify.save': 'שמור סיווג',
  'tender.classify.saving': 'שומר...',
  'tender.classify.saved': 'הסיווג נשמר',
  'tender.classify.failed': 'השמירה נכשלה',
  'tender.classify.hint': 'סיווג הדרגתי: אפשר למלא רק חלק מהשדות ולחזור בהמשך',
  'tender.classify.date': 'תאריך אירוע',
  'tender.collection.title': 'אוסף למכרז',
  'tender.collection.none': 'אין אוסף פעיל. צרו אוסף חדש כדי להתחיל לאסוף',
  'tender.collection.new': 'אוסף חדש',
  'tender.collection.new.placeholder': 'שם האוסף...',
  'tender.collection.create': 'צור',
  'tender.collection.rename': 'שנה שם',
  'tender.collection.rename.save': 'שמור',
  'tender.collection.galleries': 'גלריות',
  'tender.collection.images': 'תמונות',
  'tender.collection.empty': 'האוסף ריק. הוסיפו גלריות או תמונות מהתוצאות',
  'tender.collection.copy': 'העתק רשימה',
  'tender.collection.copied': 'הרשימה הועתקה',
  'tender.collection.copy_failed': 'ההעתקה נכשלה',
  'tender.collection.whole_gallery': 'כל הגלריה',
  'tender.collection.remove': 'הסר',
  'tender.collection.select': 'בחר אוסף',
  'tender.collection.load_failed': 'טעינת האוספים נכשלה. ייתכן שהעדכון למסד הנתונים עדיין לא הותקן',
} as const

export type TenderKey = keyof typeof he

const en: Record<TenderKey, string> = {
  'tender.title': 'Tender library',
  'tender.subtitle': 'Filter the archive by event traits, collect galleries and images, and export a list for your proposal',
  'tender.search.placeholder': 'Search by gallery name, client or location...',
  'tender.filters.event_type': 'Event type',
  'tender.filters.size': 'Event size',
  'tender.filters.industry': 'Industry',
  'tender.filters.industry.placeholder': 'e.g. tech, finance...',
  'tender.filters.client': 'Client',
  'tender.filters.client.any': 'All clients',
  'tender.filters.location': 'Location',
  'tender.filters.location.placeholder': 'City or venue...',
  'tender.filters.venue': 'Venue type',
  'tender.filters.time': 'Time of day',
  'tender.filters.years': 'Year range',
  'tender.filters.year_from': 'From year',
  'tender.filters.year_to': 'To year',
  'tender.filters.keywords': 'Keywords',
  'tender.filters.keywords.placeholder': 'Comma separated...',
  'tender.filters.any': 'Any',
  'tender.filters.clear': 'Clear filters',
  'tender.orientation': 'Orientation',
  'tender.orientation.any': 'Any',
  'tender.orientation.portrait': 'Portrait',
  'tender.orientation.landscape': 'Landscape',
  'tender.size.intimate': 'Intimate (up to 50)',
  'tender.size.small': 'Small (50-150)',
  'tender.size.medium': 'Medium (150-500)',
  'tender.size.large': 'Large (500-2000)',
  'tender.size.massive': 'Massive (2000+)',
  'tender.venue.indoor': 'Indoor',
  'tender.venue.outdoor': 'Outdoor',
  'tender.venue.mixed': 'Mixed',
  'tender.time.day': 'Day',
  'tender.time.night': 'Night',
  'tender.time.mixed': 'Mixed',
  'tender.results.count': 'galleries',
  'tender.results.one': 'gallery',
  'tender.results.empty': 'No galleries match this search',
  'tender.results.loading': 'Searching...',
  'tender.results.error': 'Search failed, please try again',
  'tender.results.search_hint': 'Type a search or pick a filter to see results',
  'tender.match.title': 'Why it matched:',
  'tender.match.name': 'Gallery name',
  'tender.match.client': 'Client',
  'tender.match.event_type': 'Event type',
  'tender.match.event_location': 'Location',
  'tender.match.event_size_bucket': 'Size',
  'tender.match.industry': 'Industry',
  'tender.match.venue_type': 'Venue',
  'tender.match.time_of_day': 'Time of day',
  'tender.match.year': 'Year',
  'tender.match.keywords': 'Keywords',
  'tender.gallery.open': 'Open gallery',
  'tender.gallery.pick_images': 'Pick images',
  'tender.gallery.close_images': 'Close images',
  'tender.gallery.add_to_collection': 'Add to collection',
  'tender.gallery.in_collection': 'In collection',
  'tender.gallery.remove_from_collection': 'Remove from collection',
  'tender.gallery.images': 'images',
  'tender.gallery.status.live': 'Published',
  'tender.gallery.status.draft': 'Draft',
  'tender.gallery.no_client': 'No client',
  'tender.ai_order': 'Based on existing AI score',
  'tender.manual_order': 'Gallery order',
  'tender.unclassified': 'Unclassified',
  'tender.classify': 'Classify event',
  'tender.classify.close': 'Close',
  'tender.classify.save': 'Save classification',
  'tender.classify.saving': 'Saving...',
  'tender.classify.saved': 'Classification saved',
  'tender.classify.failed': 'Save failed',
  'tender.classify.hint': 'Gradual enrichment: fill only some fields and come back later',
  'tender.classify.date': 'Event date',
  'tender.collection.title': 'Tender collection',
  'tender.collection.none': 'No active collection. Create one to start collecting',
  'tender.collection.new': 'New collection',
  'tender.collection.new.placeholder': 'Collection name...',
  'tender.collection.create': 'Create',
  'tender.collection.rename': 'Rename',
  'tender.collection.rename.save': 'Save',
  'tender.collection.galleries': 'galleries',
  'tender.collection.images': 'images',
  'tender.collection.empty': 'Collection is empty. Add galleries or images from the results',
  'tender.collection.copy': 'Copy list',
  'tender.collection.copied': 'List copied',
  'tender.collection.copy_failed': 'Copy failed',
  'tender.collection.whole_gallery': 'Whole gallery',
  'tender.collection.remove': 'Remove',
  'tender.collection.select': 'Pick collection',
  'tender.collection.load_failed': 'Loading collections failed. The database update may not be installed yet',
}

const dict: Record<Locale, Record<TenderKey, string>> = { he, en }

export function t(locale: Locale, key: TenderKey): string {
  return dict[locale][key] ?? dict.he[key] ?? key
}
